### ISSUE TITLE
Error when running "node index.js"

### ISSUE THREAD

**Issue by njmurarka** [mushroomgenie/DiscordBluzelleBot#5]
`
Vega:DiscordBluzelleBot loquitus$ node index.js
file:///Users/loquitus/src/ff/DiscordBluzelleBot/index.js:11
const sdk = await bluzelle({
            ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
`

**Comment by njmurarka** [comment]
This is on MacOS.

**Comment by njmurarka** [comment]
Tests passed. But bot won't run.

**Comment by mushroomgenie** [comment]
Did you create a `.env` file with `BOT_TOKEN` and `MNEMONIC` ?

**Comment by mushroomgenie** [comment]
@njmurarka Which version of Node are you using?

**Comment by mushroomgenie** [comment]
@njmurarka You might wanna take a look at this to upgrade your node version on MacOS - https://stackoverflow.com/questions/11284634/upgrade-node-js-to-the-latest-version-on-mac-os

**Comment by njmurarka** [comment]
Seems to not happen on Ubuntu
